# IMPORTING LIBRARY 


In [ ]:
import numpy as np

# Question 01: Create a NumPy Array 🟢

**Task:** Write a program that imports NumPy as `np`, creates a NumPy array containing `[10, 20, 30, 40, 50]`, and prints the array.

---

### 📋 Requirements

1. **Importing NumPy:** Import the package using the conventional alias `import numpy as np`.
2. **Array Creation:** Use `np.array()` passing a standard Python list `[10, 20, 30, 40, 50]`.
3. **Display:** Print the generated array object.

---

### 📥 Example Walkthrough

```text
Array: [10 20 30 40 50]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Using NumPy arrays over standard Python lists offers contiguous memory storage and optimized C-level vector operations.

---

### 💻 Your Code Solution

```python

```

In [ ]:
array=np.array([10,20,30,40,50])
print("Array=", array)

# Question 02: Array Creation Functions 🟢

**Task:** Create and print arrays using NumPy built-in creation routines: zeros, ones, constant values, integer ranges, and linearly spaced values.

---

### 📋 Requirements

1. **Zeros:** Use `np.zeros(5)` to create an array of five `0.0` elements.
2. **Ones:** Use `np.ones(5)` to create an array of five `1.0` elements.
3. **Full Constant:** Use `np.full(5, 7)` to fill an array with `7`s.
4. **Range:** Use `np.arange(1, 11)` to generate numbers from 1 to 10.
5. **Linspace:** Use `np.linspace(0, 1, 5)` to generate 5 equally spaced values between 0 and 1.

---

### 📥 Example Walkthrough

```text
Zeros    : [0. 0. 0. 0. 0.]
Ones     : [1. 1. 1. 1. 1.]
Full (7) : [7 7 7 7 7]
Arange   : [ 1  2  3  4  5  6  7  8  9 10]
Linspace : [0.   0.25 0.5  0.75 1.  ]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `np.arange(start, stop, step)` excludes the `stop` value, whereas `np.linspace(start, stop, num)` includes the `stop` boundary by default.

---

### 💻 Your Code Solution

```python

```

In [ ]:
print(f"Zeros : {np.zeros(5)}")
print(f"Ones : {np.ones(5)}")
print(f"Full (7) : {np.full(5,7)}")
print(f"Arrange : {np.arange(1,11)}")
print(f"Linspace : {np.linspace(0,1,5)}")

# Question 03: Different Data Types 🟢

**Task:** Create NumPy arrays containing integers, floating-point numbers, and boolean values. Print each array along with its `.dtype` property.

---

### 📋 Requirements

1. **Integer Array:** Create an array with integers like `[1, 2, 3]`.
2. **Float Array:** Create an array with floats like `[1.5, 2.5, 3.5]`.
3. **Boolean Array:** Create an array with booleans like `[True, False, True]`.
4. **Attribute Check:** Print each array along with its corresponding `.dtype` attribute.

---

### 📥 Example Walkthrough

```text
Int Array   : [1 2 3] | Data Type: int64 (or int32)
Float Array : [1.5 2.5 3.5] | Data Type: float64
Bool Array  : [ True False  True] | Data Type: bool
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** NumPy arrays enforce strict type homogeneity. Mixing data types inside an array results in automatic type casting (coercion) to the most general type.

---

### 💻 Your Code Solution

```python

```


In [ ]:
print(f"Int Array : {np.arange(1,4)}")
print(f"Float Array : {np.array([1.5, 2.5, 3.5])}")
print(f"Boolean Array : {np.array([True, False, True])}")

# Question 04: Random Array 🟢

**Task:** Generate a 1D array containing 10 random integers between 1 and 100, and a 2D array of shape 3×3 containing random integers between 1 and 50.

---

### 📋 Requirements

1. **1D Random Integers:** Use `np.random.randint(1, 101, size=10)` to draw 10 values in range `[1, 100]`.
2. **2D Random Matrix:** Use `np.random.randint(1, 51, size=(3, 3))` to create a 3x3 array with random integers in range `[1, 50]`.
3. **Display:** Print both generated random arrays.

---

### 📥 Example Walkthrough

```text
1D Random Array:
[42 18 89 73  5 91 34 62 11 50]

2D Random Array (3x3):
[[24 12 45]
 [ 3 38 19]
 [50  8 31]]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** In `np.random.randint(low, high, size)`, the upper bound `high` is exclusive, so use `101` and `51` to include `100` and `50`.

---

### 💻 Your Code Solution

```python

```

In [ ]:
print(f"1D Random Array:\n{np.random.randint(1,101,size=10)}")
print(f"1D Random Array:\n{np.random.randint(1,101,size=(3,3))}")

# Question 05: Array Properties 🟢

**Task:** Create the 2D array `[[10, 20, 30], [40, 50, 60]]` and print its core metadata attributes: `ndim`, `shape`, `size`, `dtype`, and `itemsize`.

---

### 📋 Requirements

1. **Array Creation:** Define `arr = np.array([[10, 20, 30], [40, 50, 60]])`.
2. **Attributes:** Access and print `arr.ndim`, `arr.shape`, `arr.size`, `arr.dtype`, and `arr.itemsize`.

---

### 📥 Example Walkthrough

```text
Dimensions (ndim) : 2
Shape             : (2, 3)
Total Elements    : 6
Data Type         : int64 (or int32)
Item Size (bytes) : 8 (or 4)
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `itemsize` returns the memory footprint of a single element in bytes, while `size * itemsize` gives total array byte size.

---

### 💻 Your Code Solution

```python

```

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(f"Dimensions (ndim) : {arr.ndim}")
print(f"Shape (ndim) : {arr.shape}")
print(f"Total Elements : {arr.size}")
print(f"Data Types : {arr.dtype}")
print(f"Item Size (bytes) : {arr.itemsize}")

# Question 06: 1D, 2D and 3D Arrays 🟢

**Task:** Construct a 1D array, 2D array, and 3D array. Print each array along with its `.ndim` and `.shape` properties.

---

### 📋 Requirements

1. **1D Array:** `np.array([1, 2, 3])` -> Shape `(3,)`, ndim `1`.
2. **2D Array:** `np.array([[1, 2], [3, 4]])` -> Shape `(2, 2)`, ndim `2`.
3. **3D Array:** `np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])` -> Shape `(2, 2, 2)`, ndim `3`.

---

### 📥 Example Walkthrough

```text
1D Array:
[1 2 3]
ndim: 1 | shape: (3,)

2D Array:
[[1 2]
 [3 4]]
ndim: 2 | shape: (2, 2)

3D Array:
[[[1 2]
  [3 4]]
 [[5 6]
  [7 8]]]
ndim: 3 | shape: (2, 2, 2)
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** The `ndim` attribute corresponds directly to the length of the `shape` tuple.

---

### 💻 Your Code Solution

```python

```

In [ ]:
print(f"1D Array:")
oned_array=np.array([1,2,3])
print(oned_array)
print(f"ndim: {oned_array.ndim} | shape: {oned_array.shape}")
print(f"2D Array:")
twod_array=np.random.randint(1,99,size=(3,3))
print(twod_array)
print(f"ndim: {twod_array.ndim} | shape: {twod_array.shape}")
print(f"3D Array:")
threed_array=np.random.randint(1,99,size=(4,4,4))
print(threed_array)
print(f"ndim: {threed_array.ndim} | shape: {threed_array.shape}")

# Question 07: Analyze an Array 🟢

**Task:** Create a 4 × 5 NumPy array containing numbers from 1 to 20 and output a clean summary report displaying its array structure, dimensions, shape, total element count, and data type.

---

### 📋 Requirements

1. **Array Generation:** Use `np.arange(1, 21).reshape(4, 5)`.
2. **Summary Printing:** Print formatted metadata tags corresponding to the array's attributes.

---

### 📥 Example Walkthrough

```text
Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Dimensions    : 2
Shape         : (4, 5)
Total Elements: 20
Data Type     : int64
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Combining `np.arange()` with `.reshape()` allows quick generation of multi-dimensional sequential test data.

---

### 💻 Your Code Solution

```python

```

In [ ]:
array=np.arange(1,21).reshape(4,5)
print(f"Array:\n{array}")
print(f"Dimensions : {array.ndim}")
print(f"Shape : {array.shape}")
print(f"Total Elements : {array.size}")
print(f"Data Type : {array.dtype}")

# Question 08: Basic Indexing 🟡

**Task:** Given `arr = np.array([10, 20, 30, 40, 50])`, print the first element, last element, third element, and second-last element using positive and negative indexing.

---

### 📋 Requirements

1. **First Element:** Access `arr[0]`.
2. **Last Element:** Access `arr[-1]`.
3. **Third Element:** Access `arr[2]`.
4. **Second-Last Element:** Access `arr[-2]`.

---

### 📥 Example Walkthrough

```text
First element       : 10
Last element        : 50
Third element       : 30
Second-last element : 40
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** NumPy arrays support zero-based indexing alongside negative indices for accessing elements relative to the end of the array.

---

### 💻 Your Code Solution

```python

```

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(f"First Element: {arr[0]}")
print(f"Last Element: {arr[-1]}")
print(f"Third Element: {arr[2]}")
print(f"Second Last Element: {arr[-2]}")

# Question 09: Slicing 🟡

**Task:** Given `arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])`, perform 1D array slicing operations.

---

### 📋 Requirements

1. **First 4 elements:** `arr[:4]`
2. **Last 3 elements:** `arr[-3:]`
3. **Index 2 to 5:** `arr[2:6]`
4. **Every second element:** `arr[::2]`
5. **Reverse order:** `arr[::-1]`

---

### 📥 Example Walkthrough

```text
First 4 elements   : [10 20 30 40]
Last 3 elements    : [60 70 80]
Index 2 to 5       : [30 40 50 60]
Every 2nd element  : [10 30 50 70]
Reversed           : [80 70 60 50 40 30 20 10]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Slicing syntax follows `[start:stop:step]`. Omission of boundaries defaults `start` to `0` and `stop` to array length.

---

### 💻 Your Code Solution

```python

```

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(f"First 4 Elements: {arr[:4]}")
print(f"Last 3 Elements: {arr[-3:]}")
print(f"Index 2 to 5: {arr[2:6]}")
print(f"Every 2nd Element: {arr[::2]}")
print(f"Reverse Element: {arr[::-1]}")

# Question 10: 2D Indexing 🟡

**Task:** Given a 3x3 2D array, perform row, column, and scalar indexing operations.

---

### 📋 Requirements

1. **Array Creation:** `arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`
2. **Specific Elements:** Access `50` (`arr[1, 1]`) and `90` (`arr[2, 2]`).
3. **Rows:** Slice first row (`arr[0, :]`) and last row (`arr[-1, :]`).
4. **Columns:** Slice first column (`arr[:, 0]`) and last column (`arr[:, -1]`).

---

### 📥 Example Walkthrough

```text
Element 50   : 50
Element 90   : 90
First Row    : [10 20 30]
Last Row     : [70 80 90]
First Column : [10 40 70]
Last Column  : [30 60 90]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Use comma-separated index tuples `arr[row, col]` for multi-dimensional array access rather than double bracket syntax `arr[row][col]`.

---

### 💻 Your Code Solution

```python

```

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(f"Element 50 : {arr[1,1]}")
print(f"Element 90 : {arr[2,2]}")
print(f"First Row : {arr[0,:]}")
print(f"last Row : {arr[-1,:]}")
print(f"First Column : {arr[:,0]}")
print(f"Last Column : {arr[:,-1]}")

# Question 11: Boolean Indexing 🟡

**Task:** Given `arr = np.array([10, 25, 40, 55, 70, 85, 100])`, apply logical condition masks to extract elements.

---

### 📋 Requirements

1. **Greater than 50:** `arr[arr > 50]`
2. **Less than 50:** `arr[arr < 50]`
3. **Even values:** `arr[arr % 2 == 0]`
4. **Between 30 and 90:** `arr[(arr >= 30) & (arr <= 90)]`

---

### 📥 Example Walkthrough

```text
Greater than 50  : [ 55  70  85 100]
Less than 50     : [10 25 40]
Even values      : [ 10  40  70 100]
Between 30 & 90  : [40 55 70 85]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** When combining bitwise Boolean conditions (`&`, `|`), parenthesize each condition expression explicitly to avoid operator precedence errors.

---

### 💻 Your Code Solution

```python

```

# Question 12: Arithmetic Operations 🟡

**Task:** Perform element-wise addition, subtraction, multiplication, division, and exponentiation on two matching 1D NumPy arrays.

---

### 📋 Requirements

1. **Arrays:** `arr1 = np.array([10, 20, 30, 40, 50])`, `arr2 = np.array([1, 2, 3, 4, 5])`
2. **Vectorized Math:** Compute `arr1 + arr2`, `arr1 - arr2`, `arr1 * arr2`, `arr1 / arr2`, and `arr1 ** arr2`.

---

### 📥 Example Walkthrough

```text
Addition       : [11 22 33 44 55]
Subtraction    : [ 9 18 27 36 45]
Multiplication : [ 10  40  90 160 250]
Division       : [10. 10. 10. 10. 10.]
Power          : [      10      400    27000  2560000 31250000]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Standard arithmetic operators perform fast element-wise C-vectorized loops across matching shapes without requiring explicit Python `for` loops.

---

### 💻 Your Code Solution

```python

```

# Question 13: Comparison Operations 🟡

**Task:** Given `arr = np.array([10, 20, 30, 40, 50])`, evaluate relational comparison operations.

---

### 📋 Requirements

1. **GreaterThan 25:** Evaluate `arr > 25` and filter elements with `arr[arr > 25]`.
2. **LessThan 40:** Evaluate `arr < 40` and filter elements with `arr[arr < 40]`.
3. **Equal 30:** Evaluate `arr == 30`.
4. **GreaterOrEqual 30:** Evaluate `arr >= 30`.

---

### 📥 Example Walkthrough

```text
Values > 25  : [30 40 50]
Values < 40  : [10 20 30]
Values == 30 : [30]
Values >= 30 : [30 40 50]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Comparison operators applied directly to a NumPy array evaluate element-wise and return a Boolean mask array of the same shape.

---

### 💻 Your Code Solution

```python

```

# Question 14: Statistical Operations 🟡

**Task:** Given `marks = np.array([65, 72, 81, 55, 90, 68, 74, 88])`, compute statistical metrics using NumPy methods.

---

### 📋 Requirements

1. **Sum:** `np.sum(marks)`
2. **Mean:** `np.mean(marks)`
3. **Median:** `np.median(marks)`
4. **Min/Max:** `np.min(marks)`, `np.max(marks)`
5. **Standard Deviation:** `np.std(marks)`
6. **Variance:** `np.var(marks)`

---

### 📥 Example Walkthrough

```text
Sum                : 593
Mean               : 74.125
Median             : 73.0
Min / Max          : 55 / 90
Standard Deviation : 10.873
Variance           : 118.234
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** NumPy statistical functions utilize vector instructions, enabling fast computations across millions of numeric items.

---

### 💻 Your Code Solution

```python

```

# Question 15: Student Marks Analysis 🟡

**Task:** Given student marks array `[45, 67, 89, 72, 91, 56, 78, 84, 63, 95]`, perform basic statistical summary and conditional group filtering.

---

### 📋 Requirements

1. **Summary Statistics:** Compute overall average, highest, and lowest score.
2. **Above Average:** Compute `marks[marks > avg]`.
3. **Below Average:** Compute `marks[marks < avg]`.

---

### 📥 Example Walkthrough

```text
Average Marks         : 73.5
Highest Marks         : 95
Lowest Marks          : 45
Students Above Average: [89 91 78 84 95]
Students Below Average: [45 67 72 56 63]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Combining aggregate summary metrics like `np.mean()` with Boolean filtering enables concise data analysis patterns in two lines of code.

---

### 💻 Your Code Solution

```python

```

# Question 16: Understand Axis 🔴

**Task:** Given a 3x3 matrix of student marks, compute column-wise and row-wise sums, averages, and maximum values using `axis=0` and `axis=1`.

---

### 📋 Requirements

1. **Matrix:** `marks = np.array([[80, 70, 90], [60, 85, 75], [90, 95, 88]])`
2. **Column Operations (`axis=0`):** Compute `np.sum(marks, axis=0)`, `np.mean(marks, axis=0)`, `np.max(marks, axis=0)`.
3. **Row Operations (`axis=1`):** Compute `np.sum(marks, axis=1)`, `np.mean(marks, axis=1)`, `np.max(marks, axis=1)`.

---

### 📥 Example Walkthrough

```text
Sum per Column (axis=0) : [230 250 253]
Sum per Row (axis=1)    : [240 220 273]
Mean per Column         : [76.67 83.33 84.33]
Mean per Row            : [80.0 73.33 91.0]
Max per Column          : [90 95 90]
Max per Row             : [90 85 95]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `axis=0` operates vertically down columns, collapsing rows. `axis=1` operates horizontally across rows, collapsing columns.

---

### 💻 Your Code Solution

```python

```

# Question 17: Subject Analysis 🔴

**Task:** Given student marks across Python, Math, and Statistics, perform subject-level and student-level aggregate statistical analysis.

---

### 📋 Requirements

1. **Data:** `marks = np.array([[80, 75, 90], [65, 88, 72], [92, 81, 85], [70, 68, 76]])`
2. **Subject Averages:** Compute mean along columns (`axis=0`).
3. **Student Totals & Means:** Compute sum and mean along rows (`axis=1`).
4. **Highest Marks per Subject:** Compute max along columns (`axis=0`).

---

### 📥 Example Walkthrough

```text
Python Avg : 76.75 | Math Avg : 78.0 | Stats Avg : 80.75
Student Totals : [245 225 258 214]
Student Averages : [81.67 75.0  86.0  71.33]
Highest Marks per Subject : [92 88 90]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Mapping domain entities (e.g., rows=students, columns=subjects) directly to `axis` parameters makes multi-dimensional aggregation intuitive.

---

### 💻 Your Code Solution

```python

```

# Question 18: Reshape 🔴

**Task:** Create a 1D array of numbers from 1 to 12 (`np.arange(1, 13)`) and reshape it into dimensions 2×6, 3×4, 4×3, and 6×2.

---

### 📋 Requirements

1. **Base Array:** `arr = np.arange(1, 13)`
2. **Reshaping:** Apply `.reshape(2, 6)`, `.reshape(3, 4)`, `.reshape(4, 3)`, and `.reshape(6, 2)`.
3. **Display:** Print each transformed matrix along with its new shape.

---

### 📥 Example Walkthrough

```text
2x6 Reshape:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

3x4 Reshape:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

4x3 Reshape:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

6x2 Reshape:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** When reshaping, the total number of elements must remain constant (`new_rows * new_cols == total_size`).

---

### 💻 Your Code Solution

```python

```

# Question 19: Flatten and Ravel 🔴

**Task:** Flatten a 2D array `[[1, 2, 3], [4, 5, 6]]` using both `.flatten()` and `.ravel()`. Explain the memory/copy difference between them.

---

### 📋 Requirements

1. **Array:** `arr = np.array([[1, 2, 3], [4, 5, 6]])`
2. **Operations:** Execute `flat_arr = arr.flatten()` and `rav_arr = arr.ravel()`.
3. **Display:** Print both 1D outputs.
4. **Explanation:** Document that `.flatten()` returns a deep copy, whereas `.ravel()` returns a memory view whenever possible.

---

### 📥 Example Walkthrough

```text
Flattened : [1 2 3 4 5 6]
Raveled   : [1 2 3 4 5 6]

Difference:
- flatten() creates a brand new copy of data (modifying it doesn't affect original).
- ravel() creates a view of original data (modifying it alters the original array).
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Use `ravel()` for memory efficiency when you only need to read a 1D representation, and `flatten()` when modifying the output independently.

---

### 💻 Your Code Solution

```python

```

# Question 20: Transpose 🔴

**Task:** Transpose a 2D array `[[1, 2, 3], [4, 5, 6]]` using both the `.T` attribute and the `np.transpose()` method.

---

### 📋 Requirements

1. **Array Creation:** `arr = np.array([[1, 2, 3], [4, 5, 6]])` (Shape: 2×3)
2. **Attribute Transpose:** Use `arr.T` (Shape: 3×2)
3. **Function Transpose:** Use `np.transpose(arr)`
4. **Display:** Print the original shape, transposed array, and its new shape.

---

### 📥 Example Walkthrough

```text
Original (2x3):
[[1 2 3]
 [4 5 6]]

Transposed using .T (3x2):
[[1 4]
 [2 5]
 [3 6]]

Transposed using transpose() (3x2):
[[1 4]
 [2 5]
 [3 6]]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Transposing swaps array dimensions (`rows` become `columns` and `columns` become `rows`).

---

### 💻 Your Code Solution

```python

```

# Question 21: Concatenate 🔴

**Task:** Combine two 1D arrays `[1, 2, 3]` and `[4, 5, 6]` into a single 1D array using `np.concatenate()`.

---

### 📋 Requirements

1. **Arrays:** `a = np.array([1, 2, 3])`, `b = np.array([4, 5, 6])`
2. **Concatenation:** Pass arrays as a sequence `np.concatenate((a, b))`.
3. **Display:** Print the resulting concatenated array.

---

### 📥 Example Walkthrough

```text
Array A     : [1 2 3]
Array B     : [4 5 6]
Concatenated: [1 2 3 4 5 6]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `np.concatenate()` takes a tuple or list of arrays as its primary argument.

---

### 💻 Your Code Solution

```python

```

# Question 22: Stack Arrays 🔴

**Task:** Stack two 1D arrays `[1, 2, 3]` and `[4, 5, 6]` vertically using `np.vstack()` and horizontally using `np.hstack()`. Print shapes.

---

### 📋 Requirements

1. **Arrays:** `a = np.array([1, 2, 3])`, `b = np.array([4, 5, 6])`
2. **Vertical Stack:** `np.vstack((a, b))` -> Creates a 2x3 2D array.
3. **Horizontal Stack:** `np.hstack((a, b))` -> Creates a 1D array of length 6.
4. **Metadata:** Print output arrays alongside their `.shape` attributes.

---

### 📥 Example Walkthrough

```text
Vertical Stack (vstack):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Horizontal Stack (hstack):
[1 2 3 4 5 6]
Shape: (6,)
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `vstack()` stacks along rows (new dimension for 1D input), while `hstack()` stacks sequentially along columns.

---

### 💻 Your Code Solution

```python

```

# Question 23: Split 🔴

**Task:** Create a 1D array containing numbers 1 to 12 (`np.arange(1, 13)`) and split it into 2, 3, and 4 equal sub-arrays using `np.split()`.

---

### 📋 Requirements

1. **Array Creation:** `arr = np.arange(1, 13)`
2. **Split into 2:** `np.split(arr, 2)`
3. **Split into 3:** `np.split(arr, 3)`
4. **Split into 4:** `np.split(arr, 4)`
5. **Display:** Print each sub-array list.

---

### 📥 Example Walkthrough

```text
Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Split into 2:
[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

Split into 3:
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

Split into 4:
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `np.split()` requires that the number of splits divides the total length of the array evenly; otherwise, a `ValueError` is raised.

---

### 💻 Your Code Solution

```python

```

# Question 24: Basic Broadcasting 🔥

**Task:** Given `arr = np.array([10, 20, 30, 40, 50])`, add `5` to every element using broadcasting, then multiply every element by `2`.

---

### 📋 Requirements

1. **Array:** `arr = np.array([10, 20, 30, 40, 50])`
2. **Broadcast Add:** Compute `arr + 5`.
3. **Broadcast Multiply:** Compute `(arr + 5) * 2`.

---

### 📥 Example Walkthrough

```text
Original     : [10 20 30 40 50]
After +5     : [15 25 35 45 55]
After *2     : [30 50 70 90 110]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Broadcasting allows scalar operations to expand automatically to match the dimensions of an array without copying data.

---

### 💻 Your Code Solution

```python

```

# Question 25: Broadcasting with 2D Array 🔥

**Task:** Given a 3x3 matrix, add the 1D array `[1, 2, 3]` to every row using broadcasting.

---

### 📋 Requirements

1. **2D Matrix:** `arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`
2. **1D Vector:** `vec = np.array([1, 2, 3])`
3. **Add:** Compute `arr + vec`.

---

### 📥 Example Walkthrough

```text
Original (3x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Vector: [1 2 3]

Result:
[[11 22 33]
 [41 52 63]
 [71 82 93]]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** When broadcasting a 1D array across a 2D matrix, trailing dimensions must match or be equal to 1.

---

### 💻 Your Code Solution

```python

```

# Question 26: Broadcasting Challenge 🔥

**Task:** Given a 3x3 student marks matrix, add `5` bonus marks to all entries, then subtract `[2, 3, 1]` from the three subjects respectively.

---

### 📋 Requirements

1. **Marks:** `marks = np.array([[70, 80, 90], [60, 75, 85], [88, 92, 79]])`
2. **Bonus:** Compute `step1 = marks + 5`.
3. **Deduction:** Compute `step2 = step1 - np.array([2, 3, 1])`.

---

### 📥 Example Walkthrough

```text
Original Marks:
[[70 80 90]
 [60 75 85]
 [88 92 79]]

After +5 Bonus:
[[75 85 95]
 [65 80 90]
 [93 97 84]]

After Deductions [2, 3, 1]:
[[73 82 94]
 [63 77 89]
 [91 94 83]]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Broadcasting rules compare shapes from right to left (trailing dimensions first) to align operations.

---

### 💻 Your Code Solution

```python

```

# Question 27: Random Numbers 🟡

**Task:** Generate 10 random floats in `[0, 1]`, 10 standard normal floats, and 10 random integers in `[1, 100]`.

---

### 📋 Requirements

1. **Uniform Floats:** `np.random.rand(10)`
2. **Normal Distribution:** `np.random.randn(10)`
3. **Random Integers:** `np.random.randint(1, 101, size=10)`

---

### 📥 Example Walkthrough

```text
Random Floats (rand):
[0.23 0.87 0.45 ...]

Normal Distribution (randn):
[-0.52 1.43 -0.12 ...]

Integers (randint):
[45 12 88 91 3 67 24 50 78 33]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `rand()` sampling comes from a uniform distribution over `[0, 1)`, whereas `randn()` samples from a standard normal distribution (mean 0, variance 1).

---

### 💻 Your Code Solution

```python

```

# Question 28: Random Choice 🟡

**Task:** Select 1 subject randomly, and 5 subjects randomly with replacement from `["Python", "Math", "Statistics", "English"]`.

---

### 📋 Requirements

1. **Subjects:** `subjects = np.array(["Python", "Math", "Statistics", "English"])`
2. **Single Choice:** `np.random.choice(subjects)`
3. **5 Choices:** `np.random.choice(subjects, size=5)`

---

### 📥 Example Walkthrough

```text
Single Pick : Python
Five Picks  : ['Math' 'Python' 'English' 'Math' 'Statistics']
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** By default, `np.random.choice()` samples with replacement (`replace=True`). Pass `replace=False` to sample without replacement.

---

### 💻 Your Code Solution

```python

```

# Question 29: Seed 🟡

**Task:** Set `np.random.seed(42)` and generate 5 random integers. Demonstrate reproducibility by setting the seed again.

---

### 📋 Requirements

1. **Set Seed:** `np.random.seed(42)`
2. **Generate:** Generate 5 random integers between 1 and 100.
3. **Reset & Observe:** Set `np.random.seed(42)` again and generate 5 more. Confirm they match exactly.

---

### 📥 Example Walkthrough

```text
Run 1 (seed=42): [52 93 15 72 61]
Run 2 (seed=42): [52 93 15 72 61]

Explanation: Setting a random seed initializes the pseudo-random number generator, producing identical sequences across runs.
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Random seeds are crucial for reproducible data science experiments, machine learning model testing, and debugging.

---

### 💻 Your Code Solution

```python

```

# Question 30: Copy vs View 🔵

**Task:** Demonstrate the difference between array copies (`.copy()`) and array views (slicing) by modifying elements and inspecting the original array.

---

### 📋 Requirements

1. **Base Array:** `arr = np.array([10, 20, 30, 40, 50])`
2. **Copy:** `arr_copy = arr.copy()`; set `arr_copy[0] = 99`.
3. **View:** `arr_view = arr[:]`; set `arr_view[1] = 88`.
4. **Inspect Original:** Print `arr` to verify `arr[0]` remains `10` while `arr[1]` changed to `88`.

---

### 📥 Example Walkthrough

```text
Original before modifications : [10 20 30 40 50]
Modified Copy first element   : 99
Modified View second element  : 88
Original after modifications  : [10 88 30 40 50]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Slicing a NumPy array returns a view, not a copy. Changing values in a view mutates the original underlying data buffer!

---

### 💻 Your Code Solution

```python

```

# Question 31: Sorting 🔵

**Task:** Given student marks `[78, 45, 92, 67, 88, 55, 73]`, sort them in ascending order and find the highest and lowest scores.

---

### 📋 Requirements

1. **Array:** `marks = np.array([78, 45, 92, 67, 88, 55, 73])`
2. **Sort:** Use `sorted_marks = np.sort(marks)`.
3. **Min / Max:** Access `sorted_marks[0]` (lowest) and `sorted_marks[-1]` (highest).

---

### 📥 Example Walkthrough

```text
Original Marks : [78 45 92 67 88 55 73]
Sorted Marks   : [45 55 67 73 78 88 92]
Lowest Mark    : 45
Highest Mark   : 92
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `np.sort(arr)` returns a sorted copy of the array, while `arr.sort()` modifies the array in-place.

---

### 💻 Your Code Solution

```python

```

# Question 32: Unique Values 🔵

**Task:** Given `arr = np.array([10, 20, 10, 30, 40, 20, 50, 30, 10])`, extract all unique elements using `np.unique()`.

---

### 📋 Requirements

1. **Array:** `arr = np.array([10, 20, 10, 30, 40, 20, 50, 30, 10])`
2. **Unique Extraction:** Apply `np.unique(arr)`.
3. **Display:** Output the sorted array of unique elements.

---

### 📥 Example Walkthrough

```text
Original Array : [10 20 10 30 40 20 50 30 10]
Unique Values  : [10 20 30 40 50]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `np.unique()` automatically sorts the unique elements in ascending order.

---

### 💻 Your Code Solution

```python

```

# Question 33: where() 🔵

**Task:** Given marks `[45, 67, 82, 39, 91, 55, 73]`, use `np.where()` to locate indices of passed (`>= 50`) and failed (`< 50`) students.

---

### 📋 Requirements

1. **Array:** `marks = np.array([45, 67, 82, 39, 91, 55, 73])`
2. **Passed Indices:** `passed_idx = np.where(marks >= 50)[0]`
3. **Failed Indices:** `failed_idx = np.where(marks < 50)[0]`
4. **Extract Values:** Print `marks[passed_idx]` and `marks[failed_idx]`.

---

### 📥 Example Walkthrough

```text
Marks          : [45 67 82 39 91 55 73]
Passed Indices : [1 2 4 5 6]
Passed Marks   : [67 82 91 55 73]
Failed Indices : [0 3]
Failed Marks   : [45 39]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `np.where(condition)` returns a tuple of index arrays corresponding to `True` locations in the Boolean mask.

---

### 💻 Your Code Solution

```python

```

# Question 34: argmax() and argmin() 🔵

**Task:** Given marks `[65, 78, 92, 55, 88, 71]`, use `argmax()` and `argmin()` to locate index positions of max and min marks.

---

### 📋 Requirements

1. **Array:** `marks = np.array([65, 78, 92, 55, 88, 71])`
2. **Indices:** Compute `max_idx = np.argmax(marks)` and `min_idx = np.argmin(marks)`.
3. **Extract:** Access `marks[max_idx]` and `marks[min_idx]`.

---

### 📥 Example Walkthrough

```text
Highest Mark Index : 2 | Value : 92
Lowest Mark Index  : 3 | Value : 55
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** `argmax()` and `argmin()` return the structural index position rather than the value itself, enabling relational lookups across parallel arrays.

---

### 💻 Your Code Solution

```python

```


---

### 📥 Example Walkthrough

```text
Student Averages        : [85.   72.33 91.   58.   82.  ]
Student Totals          : [255 217 273 174 246]
Subject Averages        : Python: 74.0 | Math: 77.0 | Stats: 82.0
Highest Marks per Sub   : [90 88 95]
Lowest Marks per Sub    : [55 61 58]
Highest Total Student   : Student 3 (273)
Lowest Total Student    : Student 4 (174)
Averages > 75           : [85. 91. 82.]
Averages < 75           : [72.33 58.  ]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Combining `axis=0` and `axis=1` statistical reductions enables powerful multi-variable dataset analysis in concise code.

---

### 💻 Your Code Solution

```python

```

# Question 35: Student Performance Analyzer 🏆

**Task:** Perform multi-dimensional student performance analysis on a 5x3 grade matrix (Python, Math, Stats) using NumPy aggregate functions, axes, indexing, and Boolean filtering.

---

### 📋 Requirements

1. **Dataset:** `marks = np.array([[78, 85, 92], [65, 72, 80], [90, 88, 95], [55, 61, 58], [82, 79, 85]])`
2. **Student Metrics (`axis=1`):** Averages and totals for each student.
3. **Subject Metrics (`axis=0`):** Averages, highest, lowest, and standard deviation for each subject.
4. **Student Extremes:** Identify student index with highest total (`np.argmax`) and lowest total (`np.argmin`).
5. **Threshold Filter:** Find student averages above and below 75.

---

### 📥 Example Walkthrough

```text
Student Averages        : [85.   72.33 91.   58.   82.  ]
Student Totals          : [255 217 273 174 246]
Subject Averages        : Python: 74.0 | Math: 77.0 | Stats: 82.0
Highest Marks per Sub   : [90 88 95]
Lowest Marks per Sub    : [55 61 58]
Highest Total Student   : Student 3 (273)
Lowest Total Student    : Student 4 (174)
Averages > 75           : [85. 91. 82.]
Averages < 75           : [72.33 58.  ]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Combining `axis=0` and `axis=1` statistical reductions enables powerful multi-variable dataset analysis in concise code.

---

### 💻 Your Code Solution

```python

```

# Question 36: Final NumPy Challenge 🔥

**Task:** Build a complete Student Marks Analyzer for 10 students and 3 subjects entirely with NumPy (no Pandas!). Generate random scores, compute subject/student stats, rank students, and print a formatted summary report.

---

### 📋 Requirements

1. **Random Seed & Data Generation:** Set `np.random.seed(42)`. Generate a 10x3 matrix of random integer scores between 50 and 100 (`Python`, `Math`, `Stats`).
2. **Calculations:**
   - Student total scores and averages (`axis=1`).
   - Subject averages and standard deviations (`axis=0`).
   - Overall class mean across all elements.
   - Students above and below class mean.
   - Student rankings derived from total scores using `np.argsort()`.
3. **Formatted Report:** Display student grades, statistics, and final leaderboard cleanly.

---

### 📥 Example Walkthrough

```text
==========================================================
                 STUDENT MARKS ANALYZER                   
==========================================================
Student Grades (Python, Math, Stats):
[[88 78 64]
 [92 57 70]
 [88 68 72]
 [60 60 73]
 [85 89 71]
 [71 78 65]
 [60 73 85]
 [61 71 78]
 [98 70 82]
 [76 61 84]]

Class Overall Average : 74.23
Top Performer         : Student 9 (Total: 250)
Rankings (by Total)   : [9, 5, 1, 3, 7, 6, 8, 2, 10, 4]
```

---

### 💡 NumPy Concept Tip

> **Key Insight:** Using `np.argsort()` allows ranking items based on computed metrics like total marks without altering the underlying matrix layout.

---

### 💻 Your Code Solution

```python

```